name: CaniTreasureBox
favicon: null
layout_spectrum: 0.99749
typography_spectrum: 0.49860842851921916
title: Cani TreasureBox
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#62a8e6'
    - '#d4e2e5'
    - '#0a0a08'
    - '#ff6300'
    - '#716555'
  brandStrength: 0.05957433977164328
  lightness: 0.6673542431090027
  saturation: 0.377801779191941
  rhythmicContrast: 0.585832406533882
purpose: []
